import type { Metadata } from 'next';
import { Container, Button, Divider } from '@/components/ui';
import { SiteHeader, SiteFooter } from '@/components/chrome';
import { CHECK_LABELS, TIER_CHECKS } from '@/modules/studio/types';

export const metadata: Metadata = {
  title: 'How we verify',
  description:
    'Interior design is unregulated in India. Here is exactly what we check on every studio, what it proves, and what it does not.',
};

export default function VerificationPage() {
  return (
    <>
      <SiteHeader />

      <main>
        <section className="border-b border-[var(--color-rule)] py-10 sm:py-14">
          <Container size="narrow">
            <p className="m-0 mb-3 font-[family-name:var(--font-mono)] text-[11px] uppercase tracking-[0.16em] text-[var(--color-ink-3)]">
              How we verify
            </p>
            <h1 className="display mb-5 max-w-[17ch]">
              There is no such thing as a licensed interior designer in India.
            </h1>
            <p className="m-0 text-[17px] leading-relaxed text-[var(--color-ink-2)]">
              No statutory licence, no board exam, no register. The Council of Architecture governs
              architects only, and IIID membership is voluntary. Anyone can print a card and take
              your advance tomorrow.
            </p>
          </Container>
        </section>

        <section className="border-b border-[var(--color-rule)] py-10">
          <Container size="narrow">
            <h2 className="h2 mb-4">
              So we verify what can actually be verified.
            </h2>
            <p className="m-0 mb-4 text-[var(--color-ink-2)]">
              We can prove a business exists, that it has been trading for years, that real clients
              have worked with it, and that its sites stand up to inspection. We cannot prove
              anyone&rsquo;s taste, and we do not pretend to.
            </p>
            <p className="m-0 text-[var(--color-ink-2)]">
              Every check below appears on the studio&rsquo;s profile with its source and the date it
              was done. A badge with no date behind it is decoration.
            </p>
          </Container>
        </section>

        <section className="py-10">
          <Container size="narrow">
            <Tier
              n="Tier 1"
              name="Listed"
              summary="The studio is who it says it is."
              checks={TIER_CHECKS.LISTED}
            />
            <Tier
              n="Tier 2"
              name="Verified"
              summary="It has a real trading history, real past clients, and sites we have stood inside."
              checks={TIER_CHECKS.VERIFIED}
              note="GST filing history is the strongest cheap signal available in India — it is public, free, and a studio filing GSTR-1 and 3B monthly for two years is demonstrably operating at scale. Re-audited every six months."
            />
            <Tier
              n="Tier 3"
              name="Proven"
              summary="It has delivered through our escrow, and the record is published — good or bad."
              checks={[]}
              note="Delivery variance against committed dates, disputes upheld, and whether the materials delivered matched the materials quoted. This is the only tier that cannot be bought from a verification vendor, because it is generated by work actually done."
            />

            <div className="mt-10 border-l-2 border-[var(--color-brass)] pl-5">
              <h3 className="h3 mb-2">What we do when it goes wrong</h3>
              <p className="m-0 mb-3 text-[15px] leading-relaxed text-[var(--color-ink-2)]">
                A studio is suspended while a serious dispute is investigated, and removed
                permanently for material misrepresentation, a pattern of upheld disputes, or
                refusing a re-audit. Upheld disputes stay on the profile — we do not delete a
                studio&rsquo;s record to make the roster look better.
              </p>
              <p className="m-0 text-[15px] leading-relaxed text-[var(--color-ink-2)]">
                Studios can appeal, and the appeal is decided by someone who did not make the
                original call.
              </p>
            </div>

            <div className="mt-10 border-t border-[var(--color-rule)] pt-8">
              <Button href="/quiz" size="lg">
                Find your match
              </Button>
            </div>
          </Container>
        </section>
      </main>

      <SiteFooter />
    </>
  );
}

function Tier({
  n,
  name,
  summary,
  checks,
  note,
}: {
  n: string;
  name: string;
  summary: string;
  checks: readonly (keyof typeof CHECK_LABELS)[];
  note?: string;
}) {
  return (
    <div className="mb-9">
      <div className="mb-3 flex flex-wrap items-baseline gap-3">
        <span className="font-[family-name:var(--font-mono)] text-[11px] uppercase tracking-[0.13em] text-[var(--color-ink-3)]">
          {n}
        </span>
        <h3 className="h2">
          {name}
        </h3>
      </div>
      <p className="m-0 mb-4 text-[16px] leading-relaxed text-[var(--color-ink-2)]">{summary}</p>
      <Divider />
      {checks.length > 0 ? (
        <ul className="m-0 mt-3 grid list-none grid-cols-1 gap-1.5 p-0 sm:grid-cols-2">
          {checks.map((c) => (
            <li key={c} className="flex items-start gap-2 text-[14px] text-[var(--color-ink-2)]">
              <span className="mt-0.5 text-[var(--color-ontrack)]" aria-hidden="true">
                ✓
              </span>
              {CHECK_LABELS[c]}
            </li>
          ))}
        </ul>
      ) : null}
      {note ? (
        <p className="m-0 mt-4 text-[14px] leading-relaxed text-[var(--color-ink-3)]">{note}</p>
      ) : null}
    </div>
  );
}
